bring init template up to match the debian package

diff --git a/templates/dataloop-agent.erb b/templates/dataloop-agent.erb
--- a/templates/dataloop-agent.erb
+++ b/templates/dataloop-agent.erb
@@ -7,80 +7,129 @@
 # Default-Stop:      0 1 6
 # Description:       Dataloop Agent
 ### END INIT INFO
-<% if @apikey.is_a? String -%>
-API_KEY=<%= @apikey %>
-<% else -%>
-<% raise ArgumentError, "Expected @apikey to be a String, got '#{@apikey.inspect}:#{@apikey.class}'" -%>
-<% end -%>
-<% if @user.is_a? String -%>
-RUNAS=<%= @user %>
-<% else -%>
-  <% raise ArgumentError, "Expected @user to be a String, got '#{@user.inspect}:#{@user.class}'" -%>
-<% end -%>
-SERVER=https://www.dataloop.io
-SCRIPT="/usr/local/bin/dataloop-lin-agent --api-key $API_KEY --server $SERVER"
 
+# Source function library.
+. /lib/lsb/init-functions
+
+# clear any accidental env vars for dataloop-agent
+# set the default user, that can be override in config
+# and source and set ones from the config file
+DESC="Dataloop Agent"
+API_KEY=
+SERVER=
+USER=dataloop
+
+if [ -f /etc/dataloop/agent.conf ] ; then
+    . /etc/dataloop/agent.conf
+fi
+
+DAEMON=/usr/bin/dataloop-agent
+DAEMON_OPTS="--api-key $API_KEY --server $SERVER"
 PIDFILE=/var/run/dataloop-agent.pid
 LOGFILE=/var/log/dataloop/agent.log
 
-start() {
-  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
-    echo 'Service already running' >&2
-    return 1
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Exit if the user specified is not present
+if ! $(id $USER >/dev/null 2>&1) ;then
+  echo "User $USER not present on this system"
+  exit 1
+fi
+
+
+do_start()
+{
+  pid=$(pidofproc -p $PIDFILE $DAEMON)
+  if [ -n "$pid" ] ; then
+      log_begin_msg "$DESC already running."
+      log_end_msg 0
+      exit 0
   fi
-  echo 'Starting service…' >&2
-  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
-  su -c "$CMD" $RUNAS > "$PIDFILE"
-  echo 'Service started' >&2
+
+  log_daemon_msg "Starting dataloop-agent daemon: "
+  start-stop-daemon --make-pidfile --pidfile $PIDFILE --chuid $USER --background --start --startas /bin/bash -- -c "exec $DAEMON $DAEMON_OPTS >> $LOGFILE 2>&1"
 }
 
-stop() {
-  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
-    echo 'Service not running' >&2
-    return 0
-  fi
-  echo 'Stopping service…' >&2
+do_stop()
+{
+  log_daemon_msg "Stopping dataloop-agent daemon: "
+  start-stop-daemon --pidfile $PIDFILE --oknodo --stop
+  RC=$?
 
-  su -c "$SCRIPT --deregister" $RUNAS
+  log_daemon_msg "Deregistering dataloop-agent from $SERVER: "
+  su -c "$DAEMON $DAEMON_OPTS --deregister" $USER
 
-  if [ $? -ne 0 ]; then
-    echo "failed! "
-  else
-    echo "success"
-  fi
-
-  echo "dataloop agent stopped"
-  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
-  echo 'Service stopped' >&2
+  [ $RC -eq 0 ] && rm -f $PIDFILE
+  log_end_msg $RC
 }
 
-uninstall() {
-  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
-  local SURE
-  read SURE
-  if [ "$SURE" = "yes" ]; then
-    stop
-    rm -f "$PIDFILE"
-    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
-    update-rc.d -f <NAME> remove
-    rm -fv "$0"
-  fi
+do_reload()
+{
+  do_stop
+  do_start
+}
+
+do_status()
+{
+    start-stop-daemon --user dataloop -x $DAEMON --pidfile $PIDFILE --user $USER --status
 }
 
 case "$1" in
   start)
-    start
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
   stop)
-    stop
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC"
+    do_stop
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
-  uninstall)
-    uninstall
+  status)
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
     ;;
-  restart)
-    stop
-    start
+  #reload|force-reload)
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    #log_daemon_msg "Reloading $DESC" "$NAME"
+    #do_reload
+    #log_end_msg $?
+    #;;
+  restart|force-reload)
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
     ;;
   *)
-    echo "Usage: $0 {start|stop|restart|uninstall}"
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
+
+exit 0
